---
abstract: 'validate and process form data'
author:
  - 'Bill Moseley <mods@hank.org>'
build_requires:
  Date::Manip: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Form-Processor
requires:
  Carp: 0
  Data::Dumper: 0
  Data::UUID: 0
  DateTime: 0
  DateTime::Format::DateManip: 0
  Digest::MD5: 0
  Email::Valid: 0
  Encode: 0
  File::Temp: 0
  HTML::Tidy: 0
  Locale::Maketext: 0
  Net::CIDR: 0
  Rose::Object: 0
  Rose::Object::MakeMethods::Generic: 0
  Scalar::Util: 0
  Template::Parser: 0
  UNIVERSAL::require: 0
  base: 0
  strict: 0
  warnings: 0
version: 1.122970
