# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Form-Processor
version:      0.09
version_from: lib/Form/Processor.pm
installdirs:  site
requires:
    DateTime:                      0.34
    DateTime::Format::DateManip:   0.04
    Email::Valid:                  0
    File::Temp:                    0
    Locale::Maketext:              1.09
    Module::Find:                  0.05
    Rose::Object:                  0.015
    Scalar::Util:                  0
    Test::More:                    0
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
